
services:
  # 1. Base de données
  postgres:
    # image: 5pierre/filrouge-db:latest
    build: ./databasee
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  # 2. Backend Auth
  auth:
    # images: Nom de l'image pour Docker Hub pas utilisé pour le moment
    build: ./BACKEND/auth-service
    ports:
      - "4000:4000"
    depends_on:
      postgres: # sinon auth démarrer avant la BDD >:(
        condition: service_healthy
    env_file:
      - .env

  # 3. Backend Message
  message:
    # images: Nom de l'image pour Docker Hub pa sutilisé pour le moment
    build: ./BACKEND/message-service
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  # 4. Frontend React
  frontend:
    # images: Nom de l'image pour Docker Hub pas sutilisé pour le moment
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src # Hot Reloading
    env_file:
      - .env



volumes:
  pgdata:
