apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filrouge-ingress
spec:
  rules:
  - http:
      paths:
      # --- Route 1 : Auth ---
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 4000
      # --- Route 2 : Story ---
      - path: /api/story
        pathType: Prefix
        backend:
          service:
            name: story-service
            port:
              number: 5000
      # --- Route 3 : Frontend ---
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000